name = "Servidor Amiguos"
author = "Santiago"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1df3048b164828546fa1eedc6a19e1e348baeb6c569fa5d3efe02cbced8f22b"

[versions]
minecraft = "1.21.1"
fabric = "0.16.5"

[options]
acceptable-game-versions = ["1.21.1"]
clientside-mods = true
serverside-mods = false