name = "Servidor Amiguos"
author = "Santiago"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e90557a8806efbfd2d07cb9044a60f4d9e872fe9f8f32a7b55b83e7b1222088"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
clientside-mods = true
serverside-mods = false
