name = "Servidor Amiguos"
author = "Santiago"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc63a409960abcaf8eda57e18f79076d11647d00ab0e549922017a8fef227398"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
clientside-mods = true
serverside-mods = false
